In [42]:
import pandas as pd
import numpy as np

In [43]:
df = pd.read_csv('tour_data.csv')
df

,Unnamed: 0,Tour_Name,Tour_Type,Number_of_Reviewer,Rating,Duration,Price,Highlight,Location
0,0,31. Phare: The Cambodian Circus Show in Siem Reap,Comedy Shows,992.0,5,1 hour,18,"Siem Reap's most original, authentic live perf...","Asia, Cambodia, Siem Reap Province, Siem Reap,..."
1,1,32. Khmer Gourmet Cooking Class,Cooking Classes,55.0,5,2–3 hours,21.5,In-person guide,"Asia, Cambodia, Siem Reap Province, Siem Reap,..."
2,2,33. Koh Ker & Beng Mealea Full-Day Join-in Tour,Full-day Tours,288.0,5,9–10 hours,50,"Cold towels & Bottled water, Professional Engl...","Asia, Cambodia, Siem Reap Province, Siem Reap,..."
3,3,"34. Kampot Day Tour ""Bokor National Park""",Adventure Tours,18.0,4.5,4–5 hours,36,"Transportation: Tuk Tuk, English speaking driv...","Asia, Cambodia, Kampot Province, Kampot, Thing..."
4,4,35. Bike the Siem Reap Countryside with Local ...,Adventure Tours,308.0,5,5 hours,35,"Hotel pick up & Drop Off, Professional local E...","Asia, Cambodia, Siem Reap Province, Siem Reap,..."
...,...,...,...,...,...,...,...,...,...
3774,3774,Daily Phnom Penh to Siem Reap by private car,Private-Drivers,NaN,NaN,8 hours (approx.),$76.00,Hotel pickup and drop-off or pickup from the a...,"Phnom Penh, Cambodia"
3775,3775,Battambang 3-Day Tour,Multi-day-Tours,NaN,NaN,3 days (approx.),$305.25,"Pick up & drop off from / at your hotel, Exper...","Siem Reap, Cambodia"
3776,3776,Full-Day Siem Reap Angkor Major Temples Privat...,Bus-and-Minivan-Tours,NaN,NaN,6 to 8 hours (approx.),$107.70,"A/C Car, Fuel, English Speaking Tour Guide, Al...","Krong Siem Reap, Cambodia"
3777,3777,Full Day Kulen Mountain Biking to Waterfall,Day-Trips,NaN,NaN,9 to 12 hours (approx.),$185.89,"Kulen Pass, English adventure guide, Lunch, Sn...","Siem Reap, Cambodia"
3778,3778,Private Tour from Siem Reap to Preah Khan Komp...,Day-Trips,NaN,NaN,11 to 13 hours (approx.),$250.00,"Professional English Speaking Tour Guide, Priv...","Siem Reap Province, Cambodia"

In [44]:
df.head()

,Unnamed: 0,Tour_Name,Tour_Type,Number_of_Reviewer,Rating,Duration,Price,Highlight,Location
0,0,31. Phare: The Cambodian Circus Show in Siem Reap,Comedy Shows,992.0,5,1 hour,18,"Siem Reap's most original, authentic live perf...","Asia, Cambodia, Siem Reap Province, Siem Reap,..."
1,1,32. Khmer Gourmet Cooking Class,Cooking Classes,55.0,5,2–3 hours,21.5,In-person guide,"Asia, Cambodia, Siem Reap Province, Siem Reap,..."
2,2,33. Koh Ker & Beng Mealea Full-Day Join-in Tour,Full-day Tours,288.0,5,9–10 hours,50,"Cold towels & Bottled water, Professional Engl...","Asia, Cambodia, Siem Reap Province, Siem Reap,..."
3,3,"34. Kampot Day Tour ""Bokor National Park""",Adventure Tours,18.0,4.5,4–5 hours,36,"Transportation: Tuk Tuk, English speaking driv...","Asia, Cambodia, Kampot Province, Kampot, Thing..."
4,4,35. Bike the Siem Reap Countryside with Local ...,Adventure Tours,308.0,5,5 hours,35,"Hotel pick up & Drop Off, Professional local E...","Asia, Cambodia, Siem Reap Province, Siem Reap,..."

In [45]:
df.tail()

,Unnamed: 0,Tour_Name,Tour_Type,Number_of_Reviewer,Rating,Duration,Price,Highlight,Location
3774,3774,Daily Phnom Penh to Siem Reap by private car,Private-Drivers,NaN,NaN,8 hours (approx.),$76.00,Hotel pickup and drop-off or pickup from the a...,"Phnom Penh, Cambodia"
3775,3775,Battambang 3-Day Tour,Multi-day-Tours,NaN,NaN,3 days (approx.),$305.25,"Pick up & drop off from / at your hotel, Exper...","Siem Reap, Cambodia"
3776,3776,Full-Day Siem Reap Angkor Major Temples Privat...,Bus-and-Minivan-Tours,NaN,NaN,6 to 8 hours (approx.),$107.70,"A/C Car, Fuel, English Speaking Tour Guide, Al...","Krong Siem Reap, Cambodia"
3777,3777,Full Day Kulen Mountain Biking to Waterfall,Day-Trips,NaN,NaN,9 to 12 hours (approx.),$185.89,"Kulen Pass, English adventure guide, Lunch, Sn...","Siem Reap, Cambodia"
3778,3778,Private Tour from Siem Reap to Preah Khan Komp...,Day-Trips,NaN,NaN,11 to 13 hours (approx.),$250.00,"Professional English Speaking Tour Guide, Priv...","Siem Reap Province, Cambodia"

In [46]:
df.describe()

        Unnamed: 0  Number_of_Reviewer
count  3779.000000         1737.000000
mean   1889.000000           21.114565
std    1091.047662           84.481347
min       0.000000            1.000000
25%     944.500000            1.000000
50%    1889.000000            4.000000
75%    2833.500000           12.000000
max    3778.000000         1312.000000

In [49]:
df

,Unnamed: 0,Tour_Name,Tour_Type,Number_of_Reviewer,Rating,Duration,Price,Highlight,Location
0,0,31. Phare: The Cambodian Circus Show in Siem Reap,Comedy Shows,992.0,5,1 hour,18,"Siem Reap's most original, authentic live perf...","Asia, Cambodia, Siem Reap Province, Siem Reap,..."
1,1,32. Khmer Gourmet Cooking Class,Cooking Classes,55.0,5,2–3 hours,21.5,In-person guide,"Asia, Cambodia, Siem Reap Province, Siem Reap,..."
2,2,33. Koh Ker & Beng Mealea Full-Day Join-in Tour,Full-day Tours,288.0,5,9–10 hours,50,"Cold towels & Bottled water, Professional Engl...","Asia, Cambodia, Siem Reap Province, Siem Reap,..."
3,3,"34. Kampot Day Tour ""Bokor National Park""",Adventure Tours,18.0,4.5,4–5 hours,36,"Transportation: Tuk Tuk, English speaking driv...","Asia, Cambodia, Kampot Province, Kampot, Thing..."
4,4,35. Bike the Siem Reap Countryside with Local ...,Adventure Tours,308.0,5,5 hours,35,"Hotel pick up & Drop Off, Professional local E...","Asia, Cambodia, Siem Reap Province, Siem Reap,..."
...,...,...,...,...,...,...,...,...,...
3774,3774,Daily Phnom Penh to Siem Reap by private car,Private-Drivers,NaN,NaN,8 hours (approx.),$76.00,Hotel pickup and drop-off or pickup from the a...,"Phnom Penh, Cambodia"
3775,3775,Battambang 3-Day Tour,Multi-day-Tours,NaN,NaN,3 days (approx.),$305.25,"Pick up & drop off from / at your hotel, Exper...","Siem Reap, Cambodia"
3776,3776,Full-Day Siem Reap Angkor Major Temples Privat...,Bus-and-Minivan-Tours,NaN,NaN,6 to 8 hours (approx.),$107.70,"A/C Car, Fuel, English Speaking Tour Guide, Al...","Krong Siem Reap, Cambodia"
3777,3777,Full Day Kulen Mountain Biking to Waterfall,Day-Trips,NaN,NaN,9 to 12 hours (approx.),$185.89,"Kulen Pass, English adventure guide, Lunch, Sn...","Siem Reap, Cambodia"
3778,3778,Private Tour from Siem Reap to Preah Khan Komp...,Day-Trips,NaN,NaN,11 to 13 hours (approx.),$250.00,"Professional English Speaking Tour Guide, Priv...","Siem Reap Province, Cambodia"

### <font color = yellow> Information of data

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3779 entries, 0 to 3778
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          3779 non-null   int64
 1   Tour_Name           3779 non-null   object
 2   Tour_Type           3777 non-null   object
 3   Number_of_Reviewer  1737 non-null   float64
 4   Rating              1737 non-null   object
 5   Duration            3778 non-null   object
 6   Price               3543 non-null   object
 7   Highlight           3779 non-null   object
 8   Location            3748 non-null   object
dtypes: float64(1), int64(1), object(7)
memory usage: 265.8+ KB

### <font color = yellow>Describe statistics

In [73]:
df.describe()

        Unnamed: 0  Number_of_Reviewer
count  3779.000000         1737.000000
mean   1889.000000           21.114565
std    1091.047662           84.481347
min       0.000000            1.000000
25%     944.500000            1.000000
50%    1889.000000            4.000000
75%    2833.500000           12.000000
max    3778.000000         1312.000000

In [74]:
df.describe(include=['object'])

,Tour_Name,Tour_Type,Rating,Duration,Price,Highlight,Location
count,3779,3777,1737,3778,3543,3779,3748
unique,3754,174,17,239,1331,2500,52
top,Angkor Wat and Small Circuit Temples by Privat...,Bus Tours,5,6+ hours,25,"Air-conditioned vehicle, English tour guide, C...","Asia, Cambodia, Siem Reap Province, Siem Reap,..."
freq,3,780,918,516,60,38,1898

In [75]:
df.describe(include=['int64'])

        Unnamed: 0
count  3779.000000
mean   1889.000000
std    1091.047662
min       0.000000
25%     944.500000
50%    1889.000000
75%    2833.500000
max    3778.000000

In [76]:
df.describe(include=['float'])

       Number_of_Reviewer
count         1737.000000
mean            21.114565
std             84.481347
min              1.000000
25%              1.000000
50%              4.000000
75%             12.000000
max           1312.000000

### <font color = yellow>Checking missing value

In [77]:
df.isna().sum()

Unnamed: 0               0
Tour_Name                0
Tour_Type                2
Number_of_Reviewer    2042
Rating                2042
Duration                 1
Price                  236
Highlight                0
Location                31
dtype: int64

In [85]:
data_missing = [feature 
                for feature in df.columns
                  if df[feature].isnull().sum]
for feature in data_missing:
  print(feature,np.round(df[feature].isnull().mean()*100),'% missing value')

Unnamed: 0 0.0 % missing value
Tour_Name 0.0 % missing value
Tour_Type 0.0 % missing value
Number_of_Reviewer 54.0 % missing value
Rating 54.0 % missing value
Duration 0.0 % missing value
Price 6.0 % missing value
Highlight 0.0 % missing value
Location 1.0 % missing value

In [78]:
# filling missing value
df['Location'].fillna(value='NaN', inplace=True)

### <font color = yellow>Checking Outlier

In [79]:
df['Number_of_Reviewer'] = pd.to_numeric(df['Number_of_Reviewer'], errors='coerce')
print(df['Number_of_Reviewer'].min())
print(df['Number_of_Reviewer'].max())

1.0
1312.0

In [80]:
Q1 = df['Number_of_Reviewer'].quantile(0.25)
Q2 = df['Number_of_Reviewer'].median()
Q3 = df['Number_of_Reviewer'].quantile(0.75)
print([Q1,Q2,Q3])

[1.0, 4.0, 12.0]

In [81]:
IQR = Q3-Q1
IQR

11.0

In [82]:
outlier_set = df[(df['Number_of_Reviewer'] < (Q1 - 1.5 * IQR)) | (df['Number_of_Reviewer'] > (Q3 + 1.5 * IQR))]
outlier_set

,Unnamed: 0,Tour_Name,Tour_Type,Number_of_Reviewer,Rating,Duration,Price,Highlight,Location
0,0,31. Phare: The Cambodian Circus Show in Siem Reap,Comedy Shows,992.0,5,1 hour,18,"Siem Reap's most original, authentic live perf...","Asia, Cambodia, Siem Reap Province, Siem Reap,..."
1,1,32. Khmer Gourmet Cooking Class,Cooking Classes,55.0,5,2–3 hours,21.5,In-person guide,"Asia, Cambodia, Siem Reap Province, Siem Reap,..."
2,2,33. Koh Ker & Beng Mealea Full-Day Join-in Tour,Full-day Tours,288.0,5,9–10 hours,50,"Cold towels & Bottled water, Professional Engl...","Asia, Cambodia, Siem Reap Province, Siem Reap,..."
4,4,35. Bike the Siem Reap Countryside with Local ...,Adventure Tours,308.0,5,5 hours,35,"Hotel pick up & Drop Off, Professional local E...","Asia, Cambodia, Siem Reap Province, Siem Reap,..."
5,5,36. Explore Battambang full day tour by Tuk Tu...,Full-day Tours,74.0,5,8–10 hours,20,"Bottled water, Include Entrance fee of killing...","Asia, Cambodia, Battambang Province, Battamban..."
...,...,...,...,...,...,...,...,...,...
3302,3302,Angkor Wat Private Driver Tours to Angkor Wat ...,Day-Trips,30.0,star-5,7 to 8 hours (approx.),NaN,"Air-conditioned vehicle, Private transportatio...","Svay Dangkum, Cambodia"
3317,3317,Private Angkor Temples Walking Tour from Siem ...,Hiking-and-Camping Tours,36.0,star-5,8 hours (approx.),$42.00,"Professional English-speaking local guide, Hot...","Siem Reap, Cambodia"
3320,3320,Angkor Wat Private Tour with Sunset Watching,Full-day-Tours,56.0,star-5,8 hours (approx.),$51.29,"Air-conditioned vehicle, English tour guide, C...","Siem Reap, Cambodia"
3583,3583,Angkor Wat Sunrise & Ancient City Discovery,Day-Trips,34.0,star-5,9 hours (approx.),$70.00,"English speaking tour guide, Quality mountain ...","Siem Reap, Cambodia"
3584,3584,Discover Angkor Wat Complex and Cambodia's Vil...,Overnight-Tours,31.0,star-5,2 days (approx.),NaN,Air-conditioned SUV Car or Air-conditioned Min...,"Siem Reap, Cambodia"

In [83]:
pd.DataFrame(outlier_set).to_csv('Outlier.csv')

### <font color = yellow>Train set & Test Set

<b><font color = yellow>A test set</font></b> is a subset of data used to evaluate the performance of a model that has already been trained on a training set. It is important to have a separate test set to ensure that the model is not overfitting to the training data and is able to generalize well to new, unseen data.

Typically, the test set is randomly sampled from the original dataset, with a portion of the data reserved for testing and the rest used for training. The size of the test set can vary depending on the size of the original dataset, but a common practice is to use 20% of the data for testing and 80% for training.

Once the model has been trained on the training set, it is evaluated on the test set to determine its performance. The test set can also be used for parameter tuning or model selection, but care must be taken to avoid overfitting to the test data.

<b><font color = yellow>A training set</font></b> is a dataset used to train a model. It is a subset of the total dataset and is used to build the model's parameters. The remaining portion of the dataset, called the validation set, is used to evaluate the performance of the model during training, while the test set is used to evaluate the final performance of the model after it has been trained. 

Therefore, to define the training set, you need to select a subset of the available data that you will use to train your machine learning model. Typically, this involves randomly selecting a portion of the data, such as 70% or 80%, and setting it aside for training. The remaining data can be split further into a validation set and a test set. The validation set is used to monitor the performance of the model during training, while the test set is only used at the end to evaluate the final performance of the trained model. 

It is important to note that the selection of the training, validation, and test sets should be done carefully to ensure that they are representative of the overall data distribution and that the model's performance on these subsets accurately reflects its performance on new, unseen data.

In [63]:
from sklearn.model_selection import train_test_split

# Assume the data is stored in a pandas DataFrame called 'data'
x = df.drop('Rating', axis=1) # Input features (all columns except the 'Rating' column)
y = df['Rating'] # Output variable (the 'Rating' column)

# Split the data into training and test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [64]:
x_train

,Unnamed: 0,Tour_Name,Tour_Type,Number_of_Reviewer,Duration,Price,Highlight,Location
1344,1344,1405. 5-day Siem Reap deep into Angkor temples...,Bus Tours,NaN,3+ days,552.83,"Breakfast, Lunch, Dinner, Lunch, Breakfast, Br...","Asia, Cambodia, Siem Reap Province, Siem Reap,..."
1476,1476,"1537. Phnom Kulen, 1000 Linga River and Waterfall",Bus Tours,NaN,6–7 hours,130,"Local live English Speaking Guide, Hotel picku...","Asia, Cambodia, Siem Reap Province, Siem Reap,..."
1268,1268,1329. 2-Day Temples with Sunrise Small Group T...,Adventure Tours,NaN,2 days,49,2 days exploring the major temples including B...,"Asia, Cambodia, Siem Reap Province, Siem Reap,..."
3689,3689,Angkor Wat Private Trip Sunrise Tour With Brea...,Bus-and-Minivan-Tours,NaN,6 to 7 hours (approx.),$36.00,"All local taxes, Cold Water during touring, Pr...","Krong Siem Reap, Cambodia"
2989,2989,Siem Reap to Poi Pet / Poi Pet to Siem Reap (T...,Private-Drivers,NaN,3 hours (approx.),NaN,"Bottled water, Air-conditioned vehicle, Privat...","Siem Reap, Cambodia"
...,...,...,...,...,...,...,...,...
1130,1130,1191. Siem Reap Heritage Walking Tour,Walking Tours,1.0,2–4 hours,6.99,Instruction at the start,"Asia, Cambodia, Siem Reap Province, Siem Reap,..."
1294,1294,1355. 9-Day Cambodia and Thailand Private Sigh...,Bus Tours,NaN,3+ days,"3,665.00","Lunch, Breakfast, Breakfast, Breakfast, Breakf...","Asia, Cambodia, Siem Reap Province, Siem Reap,..."
860,860,921. Rooftop Romantic Dinner - 4 Courses Set M...,3 hours,4.0,3 hours,70.77,"Gourmet Set Menu, A bottle of Pre-Selected Win...","Asia, Cambodia, Siem Reap Province, Siem Reap,..."
3507,3507,Full Day Pepper Farm Adventure by Scooter,Full-day-Tours,4.0,7 hours (approx.),$45.00,"Lunch, Drinking water, Driver/guide, Use of he...","Krong Kampot, Cambodia"
3174,3174,Private 3 Day Adventure To Ancient Temples,Multi-day-Tours,1.0,3 days (approx.),NaN,"Hotel pickup and drop-off, Professional guide,...","Siem Reap, Cambodia"

In [65]:
y_train

1344       NaN
1476       NaN
1268       NaN
3689       NaN
2989       NaN
         ...
1130         4
1294       NaN
860          4
3507    star-5
3174    star-5
Name: Rating, Length: 2645, dtype: object

In [66]:
x_test

,Unnamed: 0,Tour_Name,Tour_Type,Number_of_Reviewer,Duration,Price,Highlight,Location
1288,1288,1349. Temples and Life Style (2 Days),Bus Tours,NaN,2 days,141.03,"English Speaking Guide, Air-conditioned vehicl...","Asia, Cambodia, Siem Reap Province, Siem Reap,..."
2614,2614,Amazing Apsara Dance Show with Dinner & Hotel ...,Dining-Experiences,2.0,2 hours (approx.),$38.67,"Round trip transfer by tuk tuk/ car, Dinner","Siem Reap, Cambodia"
2355,2355,2416. 2-Day Temples with Sunrise Small Group T...,Adventure Tours,NaN,2 days,50,2 days exploring the major temples including B...,"Asia, Cambodia, Siem Reap Province, Siem Reap,..."
298,298,359. Private City Tour in Siem Reap,Bus Tours,6.0,4 hours,57.7,"Hotel pickup and drop-off, Private air-conditi...","Asia, Cambodia, Siem Reap Province, Siem Reap,..."
1123,1123,1184. Kompong Phluk Half-Day Tour from Siem Reap,Bus Tours,3.0,4–5 hours,45,"Lunch, beverages and snacks, Local guide, Tran...",NaN
...,...,...,...,...,...,...,...,...
2952,2952,Full-Day private Tour with Sun Rise in Lost Ci...,Day-Trips,4.0,8 to 9 hours (approx.),$33.00,"English Speaking Tour Guide, Private confortab...","Siem Reap, Cambodia"
3525,3525,Ruin City Of Koh Ker,Overnight-Tours,NaN,2 days (approx.),$123.08,"pick up, drop of, driver, guide, water, food, ...","Siem Reap, Cambodia"
2653,2653,Countryside & Livelihood Tour by Jeep - Half-day,Day-Trips,7.0,4 to 5 hours (approx.),$55.00,"English speaking tour guide, Vintage jeep & dr...","Siem Reap, Cambodia"
1725,1725,"1786. Mechrey Floating village, Killing Fields...",Bus Tours,NaN,6–7 hours,73.08,"English-Speaking Tour Guide, Transport ( AC ca...","Asia, Cambodia, Siem Reap Province, Siem Reap,..."
3719,3719,Angkor Wat Sunrise Tour With Prediction,Full-day-Tours,NaN,9 to 10 hours (approx.),$47.44,"English-speaking Tour Guide, Transportation ( ...","Siem Reap, Cambodia"

In [67]:
y_test

1288       NaN
2614    star-3
2355       NaN
298        4.5
1123         3
         ...
2952    star-5
3525       NaN
2653    star-5
1725       NaN
3719       NaN
Name: Rating, Length: 1134, dtype: object

In [68]:
train_data = pd.concat([x_train, y_train], axis=1)
train_set = pd.DataFrame(train_data).to_csv('train_set.csv') 
data1 = pd.read_csv('train_set.csv')
data1

,Unnamed: 0.1,Unnamed: 0,Tour_Name,Tour_Type,Number_of_Reviewer,Duration,Price,Highlight,Location,Rating
0,1344,1344,1405. 5-day Siem Reap deep into Angkor temples...,Bus Tours,NaN,3+ days,552.83,"Breakfast, Lunch, Dinner, Lunch, Breakfast, Br...","Asia, Cambodia, Siem Reap Province, Siem Reap,...",NaN
1,1476,1476,"1537. Phnom Kulen, 1000 Linga River and Waterfall",Bus Tours,NaN,6–7 hours,130,"Local live English Speaking Guide, Hotel picku...","Asia, Cambodia, Siem Reap Province, Siem Reap,...",NaN
2,1268,1268,1329. 2-Day Temples with Sunrise Small Group T...,Adventure Tours,NaN,2 days,49,2 days exploring the major temples including B...,"Asia, Cambodia, Siem Reap Province, Siem Reap,...",NaN
3,3689,3689,Angkor Wat Private Trip Sunrise Tour With Brea...,Bus-and-Minivan-Tours,NaN,6 to 7 hours (approx.),$36.00,"All local taxes, Cold Water during touring, Pr...","Krong Siem Reap, Cambodia",NaN
4,2989,2989,Siem Reap to Poi Pet / Poi Pet to Siem Reap (T...,Private-Drivers,NaN,3 hours (approx.),NaN,"Bottled water, Air-conditioned vehicle, Privat...","Siem Reap, Cambodia",NaN
...,...,...,...,...,...,...,...,...,...,...
2640,1130,1130,1191. Siem Reap Heritage Walking Tour,Walking Tours,1.0,2–4 hours,6.99,Instruction at the start,"Asia, Cambodia, Siem Reap Province, Siem Reap,...",4
2641,1294,1294,1355. 9-Day Cambodia and Thailand Private Sigh...,Bus Tours,NaN,3+ days,"3,665.00","Lunch, Breakfast, Breakfast, Breakfast, Breakf...","Asia, Cambodia, Siem Reap Province, Siem Reap,...",NaN
2642,860,860,921. Rooftop Romantic Dinner - 4 Courses Set M...,3 hours,4.0,3 hours,70.77,"Gourmet Set Menu, A bottle of Pre-Selected Win...","Asia, Cambodia, Siem Reap Province, Siem Reap,...",4
2643,3507,3507,Full Day Pepper Farm Adventure by Scooter,Full-day-Tours,4.0,7 hours (approx.),$45.00,"Lunch, Drinking water, Driver/guide, Use of he...","Krong Kampot, Cambodia",star-5
2644,3174,3174,Private 3 Day Adventure To Ancient Temples,Multi-day-Tours,1.0,3 days (approx.),NaN,"Hotel pickup and drop-off, Professional guide,...","Siem Reap, Cambodia",star-5

In [69]:
test_data = pd.concat([x_test, y_test], axis=1)
test_set = pd.DataFrame(test_data).to_csv('test_set.csv') 
data2 = pd.read_csv('test_set.csv')
data2

,Unnamed: 0.1,Unnamed: 0,Tour_Name,Tour_Type,Number_of_Reviewer,Duration,Price,Highlight,Location,Rating
0,1288,1288,1349. Temples and Life Style (2 Days),Bus Tours,NaN,2 days,141.03,"English Speaking Guide, Air-conditioned vehicl...","Asia, Cambodia, Siem Reap Province, Siem Reap,...",NaN
1,2614,2614,Amazing Apsara Dance Show with Dinner & Hotel ...,Dining-Experiences,2.0,2 hours (approx.),$38.67,"Round trip transfer by tuk tuk/ car, Dinner","Siem Reap, Cambodia",star-3
2,2355,2355,2416. 2-Day Temples with Sunrise Small Group T...,Adventure Tours,NaN,2 days,50,2 days exploring the major temples including B...,"Asia, Cambodia, Siem Reap Province, Siem Reap,...",NaN
3,298,298,359. Private City Tour in Siem Reap,Bus Tours,6.0,4 hours,57.7,"Hotel pickup and drop-off, Private air-conditi...","Asia, Cambodia, Siem Reap Province, Siem Reap,...",4.5
4,1123,1123,1184. Kompong Phluk Half-Day Tour from Siem Reap,Bus Tours,3.0,4–5 hours,45,"Lunch, beverages and snacks, Local guide, Tran...",NaN,3
...,...,...,...,...,...,...,...,...,...,...
1129,2952,2952,Full-Day private Tour with Sun Rise in Lost Ci...,Day-Trips,4.0,8 to 9 hours (approx.),$33.00,"English Speaking Tour Guide, Private confortab...","Siem Reap, Cambodia",star-5
1130,3525,3525,Ruin City Of Koh Ker,Overnight-Tours,NaN,2 days (approx.),$123.08,"pick up, drop of, driver, guide, water, food, ...","Siem Reap, Cambodia",NaN
1131,2653,2653,Countryside & Livelihood Tour by Jeep - Half-day,Day-Trips,7.0,4 to 5 hours (approx.),$55.00,"English speaking tour guide, Vintage jeep & dr...","Siem Reap, Cambodia",star-5
1132,1725,1725,"1786. Mechrey Floating village, Killing Fields...",Bus Tours,NaN,6–7 hours,73.08,"English-Speaking Tour Guide, Transport ( AC ca...","Asia, Cambodia, Siem Reap Province, Siem Reap,...",NaN
1133,3719,3719,Angkor Wat Sunrise Tour With Prediction,Full-day-Tours,NaN,9 to 10 hours (approx.),$47.44,"English-speaking Tour Guide, Transportation ( ...","Siem Reap, Cambodia",NaN